const colors = require('tailwindcss/colors');

const {
    white,
    black,
    slate,
    gray,
    zinc,
    neutral,
    red,
    orange,
    amber,
    yellow,
    lime,
    green,
    emerald,
    teal,
    cyan,
    sky,
    blue,
    indigo,
    violet,
    purple,
    fuchsia,
    pink,
    rose,
} = colors;

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        fontFamily: {
            display: ['Montserrat'],
            header: ['Neucha'],
        },

        colors: {
            current: 'currentColor',
            transparent: 'transparent',
            primary: 'hsl(210, 73%, 46%)',
            'primary-light': 'hsl(210, 79%, 76%)',
            white,
            black,
            slate,
            gray,
            zinc,
            neutral,
            red,
            orange,
            amber,
            yellow,
            lime,
            green,
            emerald,
            teal,
            cyan,
            sky,
            blue,
            indigo,
            violet,
            purple,
            fuchsia,
            pink,
            rose,
        },
    },
    plugins: [require('@tailwindcss/line-clamp')],
};
